version: '3'

services:
  wordpress000ex12:
    image: wordpress
    depends_on:
      - mysql000ex11
    networks:
      - wordpress000net1
    ports:
      - 8085:80
    restart: always
    environment:
      - WORDPRESS_DB_HOST=mysql000ex11
      - WORDPRESS_DB_NAME=wordpress000db
      - WORDPRESS_DB_USER=wordpress000kun
      - WORDPRESS_DB_PASSWORD=wkunpass

## 위 도커 컴포즈 명령어를 도커 명령어로 풀면 아래와 같다.
# docker run \
# --name wordpress000ex11 \
# -dit \
# --net wordpress000net1 \
# -p 8085:80 \
# -e WORDPRESS_DB_HOST=mysql000ex11 \
# -e WORDPRESS_DB_NAME=wordpress000db \
# -e WORDPRESS_DB_USER=wordpress000kun \
# -e WORDPRESS_DB_PASSWORD=wkunpass \
# wordpress